---

name: Release to Ansible Galaxy

on:
  release:
    types: [created, edited, published, released]
jobs:
  release:
    needs:
      - molecule
    runs-on: ubuntu-20.04
    steps:
      - name: galaxy
        uses: robertdebock/galaxy-action@1.1.1
        with:
          galaxy_api_key: ${{ secrets.galaxy_api_key }}
